server:
  port: 8083
  servlet:
    context-path: /v1

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.0.172:3306/walletcoin?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: test

  redis:
    host: 192.168.0.172
    port: 6379


application:
  eth:
    eth-coinid: https://mainnet-eth.coinid.pro
  btc:
    btc-coinid: https://mainnet-btc.coinid.pro
  eos:
    eos-coinid: https://mainnet-eos.coinid.pro
  vns:
    vns-coinid: https://mainnet-gvns.coinid.pro